agents:
  PDM4ARocket: # do not change this name
    state:
      x: -8.0
      y: -8.0
      psi: -0.26179938779 
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      phi: 0.0
      m: 2.5
    goal:
      type: satellite
      name: Vegeta/Kelbo
      pos_tolerance: 0.7
      dir_tolerance: 0.5
      vel_tolerance: 1.0
    color: 'blue'

planets:
  Vegeta:
    center: [0.0, 0.0]
    radius: 3.0
    satellites:
      Kelbo:
        tau: 5.2359
        orbit_r: 8.0
        omega: 0.19454
        radius: 0.5
  Namek:
    center: [0.0, 0.0]
    radius: 3.0
    satellites:
      Cereal:
        tau: 0.0
        orbit_r: 6.0
        omega: 0.25358
        radius: 1
      Camilla:
        tau: 2.2359
        orbit_r: 2.0
        omega: 0.09454
        radius: 0.5

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]

seed: 98